// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OscarsBallot.Data;

#nullable disable

namespace OscarsBallot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("OscarsBallot.Models.Ballot", b =>
                {
                    b.Property<int>("BallotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NomineeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BallotId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NomineeId");

                    b.HasIndex("UserId", "CategoryId", "NomineeId")
                        .IsUnique();

                    b.HasIndex("UserId", "CategoryId", "Rank")
                        .IsUnique();

                    b.ToTable("Ballots", t =>
                        {
                            t.HasCheckConstraint("CK_Ballots_Rank", "Rank IN (1, 2)");
                        });
                });

            modelBuilder.Entity("OscarsBallot.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Points")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("OscarsBallot.Models.Nominee", b =>
                {
                    b.Property<int>("NomineeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("NomineeId");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique();

                    b.ToTable("Nominees");
                });

            modelBuilder.Entity("OscarsBallot.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("FirstName", "LastName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OscarsBallot.Models.Winner", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinnerNomineeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Winner_Nominee_ID");

                    b.HasKey("CategoryId");

                    b.HasIndex("WinnerNomineeId");

                    b.ToTable("Winners");
                });

            modelBuilder.Entity("OscarsBallot.Models.Ballot", b =>
                {
                    b.HasOne("OscarsBallot.Models.Category", "Category")
                        .WithMany("Ballots")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OscarsBallot.Models.Nominee", "Nominee")
                        .WithMany("Ballots")
                        .HasForeignKey("NomineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OscarsBallot.Models.User", "User")
                        .WithMany("Ballots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Nominee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OscarsBallot.Models.Nominee", b =>
                {
                    b.HasOne("OscarsBallot.Models.Category", "Category")
                        .WithMany("Nominees")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OscarsBallot.Models.Winner", b =>
                {
                    b.HasOne("OscarsBallot.Models.Category", "Category")
                        .WithOne("Winner")
                        .HasForeignKey("OscarsBallot.Models.Winner", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OscarsBallot.Models.Nominee", "WinnerNominee")
                        .WithMany("WinningCategories")
                        .HasForeignKey("WinnerNomineeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("WinnerNominee");
                });

            modelBuilder.Entity("OscarsBallot.Models.Category", b =>
                {
                    b.Navigation("Ballots");

                    b.Navigation("Nominees");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("OscarsBallot.Models.Nominee", b =>
                {
                    b.Navigation("Ballots");

                    b.Navigation("WinningCategories");
                });

            modelBuilder.Entity("OscarsBallot.Models.User", b =>
                {
                    b.Navigation("Ballots");
                });
#pragma warning restore 612, 618
        }
    }
}
